CREATE TABLE Passports(
	PassportID INT IDENTITY NOT NULL,
	PassportNumber NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_Passports PRIMARY KEY (PassportID)
)

CREATE TABLE Persons(
	PersonID INT IDENTITY NOT NULL,
	FirstName VARCHAR(60) NOT NULL,
	Salary DECIMAL(15,2) NOT NULL DEFAULT 0,
	PassportID INT NOT NULL,
	CONSTRAINT PK_Persons PRIMARY KEY (PersonID),
	CONSTRAINT FK_Persons_Passports FOREIGN KEY (PassportID) REFERENCES Passports(PassportID)
)
