CREATE TABLE Majors(
	MajorID INT IDENTITY,
	Name VARCHAR(50) NOT NULL
	CONSTRAINT PK_Majors PRIMARY KEY (MajorID)
)

CREATE TABLE Students(
	StudentID INT IDENTITY,
	StudentNumber INT NOT NULL,
	StudentName VARCHAR(50) NOT NULL,
	MajorID INT NOT NULL
	CONSTRAINT PK_Students PRIMARY KEY (StudentID),
	CONSTRAINT FK_Students_Major FOREIGN KEY (MajorID) REFERENCES Majors(MajorID)
)

CREATE TABLE Subjects(
	SubjectID INT IDENTITY,
	SubjectName VARCHAR(50) NOT NULL
	CONSTRAINT PK_Subjects PRIMARY KEY (SubjectID)
)

CREATE TABLE Agenda(
	StudentID INT NOT NULL,
	SubjectID INT NOT NULL,
	CONSTRAINT PK_Agenda PRIMARY KEY (StudentID, SubjectID),
	CONSTRAINT FK_Agenda_Students FOREIGN KEY (StudentID) REFERENCES Students(StudentID),
	CONSTRAINT FK_Agenda_Subjects FOREIGN KEY (SubjectID) REFERENCES Subjects(SubjectID)
)

CREATE TABLE Payments(
	PaymentID INT IDENTITY,
	PaymentDate DATE,
	PaymentAmount DECIMAL(15,2) NOT NULL DEFAULT 0,
	StudentID INT NOT NULL
	CONSTRAINT PK_Payments PRIMARY KEY (PaymentID),
	CONSTRAINT FK_Payments_Students FOREIGN KEY (StudentID) REFERENCES Students(StudentID)
)
